default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: toor
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: routine_development

test:
  <<: *default
  database: routine_test

production:
  <<: *default
  username: admin
  password: <%= Rails.application.credentials.dig(:mysql, :password) %>
  host: routine-db.cbgbqblndf2s.ap-northeast-1.rds.amazonaws.com
  database: routine_production
