development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: routine_development
  pool: 5
  username: toor
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: routine_test
  pool: 5
  username: toor
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: routine_production
  pool: 5
  username: toor
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost